export const themes = {
  default: {
    '--clr-header-2-bg-color': 'hsl(209, 19%, 35%)',
    '--clr-header-font-color': 'var(--clr-color-neutral-50)',
    '--clr-btn-default-bg-color': 'transparent',
    '--clr-btn-default-border-color': 'var(--clr-color-action-600)',
    '--clr-btn-default-color': 'var(--clr-color-action-600)',
    '--clr-vertical-nav-divider-color': 'var(--clr-color-neutral-700)',
    '--clr-vertical-nav-icon-active-color': 'var(--clr-color-action-600)',
    '--clr-vertical-nav-item-color': 'var(--clr-color-neutral-700)',
    '--clr-vertical-nav-item-active-color': 'var(--clr-color-neutral-700)',
    '--clr-vertical-nav-bg-color': 'var(--clr-color-neutral-200)',
    '--clr-vertical-nav-active-bg-color': 'var(--clr-color-neutral-0)',
    '--clr-vertical-nav-hover-bg-color': 'var(--clr-color-neutral-400)',
    '--clr-vertical-nav-toggle-icon-color': 'var(--clr-color-neutral-1000)',
    '--clr-vertical-nav-trigger-divider-border-color': 'var(--clr-color-neutral-400)',
  },
  blue: {
    '--clr-header-2-bg-color': 'steelblue',
    '--clr-header-font-color': 'white',
    '--clr-btn-default-bg-color': '#0BB5FF',
    '--clr-btn-default-border-color': '#0BB5FF',
    '--clr-btn-default-color': 'white',
    '--clr-vertical-nav-divider-color': 'steelblue',
    '--clr-vertical-nav-icon-active-color': 'white',
    '--clr-vertical-nav-item-color': '#26466D',
    '--clr-vertical-nav-item-active-color': 'white',
    '--clr-vertical-nav-bg-color': '#C3E4ED',
    '--clr-vertical-nav-active-bg-color': 'steelblue',
    '--clr-vertical-nav-hover-bg-color': '#0BB5FF',
    '--clr-vertical-nav-toggle-icon-color': 'steelblue',
    '--clr-vertical-nav-trigger-divider-border-color': 'steelblue',
  },
  orange: {
    '--clr-header-2-bg-color': 'orangered',
    '--clr-header-font-color': 'white',
    '--clr-btn-default-bg-color': 'transparent',
    '--clr-btn-default-border-color': 'orangered',
    '--clr-btn-default-color': 'orangered',
    '--clr-vertical-nav-divider-color': 'sepia',
    '--clr-vertical-nav-icon-active-color': 'white',
    '--clr-vertical-nav-item-color': 'sepia',
    '--clr-vertical-nav-item-active-color': 'white',
    '--clr-vertical-nav-bg-color': '#EEE8CD',
    '--clr-vertical-nav-active-bg-color': '#8B4500',
    '--clr-vertical-nav-hover-bg-color': 'orangered',
    '--clr-vertical-nav-toggle-icon-color': 'sepia',
    '--clr-vertical-nav-trigger-divider-border-color': 'sepia',
  },
};